
MALLPRODUCTS = 'products'
DODAVATELWASHER = 'washers'
DODAVAETELPIPER = 'pipers'
OFFSET = 0
MAXLISTVALUES = 2000
MALLFILEPATH = r'outputs\MALLProducts.csv'
COMPETITORSFILEPATH = r'outputs\COMPETITORSProducts.csv'
MEDIANANALYSISFILEPATH = r'outputs\MEDIANAnalysis.json'
PRODUCSTANALYSISFILEPATH = r'outputs\PRODUCTSAnalysis.csv'